### ISSUE TITLE
gtk.sh segfaults intermittently

### ISSUE THREAD

**Issue by AkihiroSuda** [taviso/ctypes.sh#30]
gtk.sh segfaults intermittently.
```
$ LANG=C gdb --eval-command=run --args bash gtk.sh 
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bash...(no debugging symbols found)...done.
Starting program: /bin/bash gtk.sh
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffed35d700 (LWP 15653)]
[New Thread 0x7fffecb5c700 (LWP 15654)]

malloc: unknown:0: assertion botched
malloc: block on free list clobbered

Program received signal SIGSEGV, Segmentation fault.
0x00000000004b9435 in ?? ()
(gdb) bt
#0  0x00000000004b9435 in ?? ()
#1  0x00007ffff3947579 in g_malloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff397b0c3 in g_variant_format_string_scan_type () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff397b15e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff397beee in g_variant_get () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff3f2efd6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007ffff3f2f613 in g_bus_get_sync () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007ffff3f05e79 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007ffff3f02f33 in g_application_register () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007ffff3f03727 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007ffff3f03a6a in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00007ffff6e1fd90 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#12 0x00007ffff6e1f7f8 in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#13 0x00007ffff70261bc in call_foreign_function (list=<optimized out>) at ctypes.c:371
#14 0x00000000004336ce in ?? ()
#15 0x000000000043586d in ?? ()
#16 0x0000000000436908 in execute_command_internal ()
#17 0x000000000043845e in execute_command ()
#18 0x000000000042137e in reader_loop ()
#19 0x000000000041fd91 in main ()
(gdb) 
```

I'm using Ubuntu 15.10 amd64.
```
$ dpkg -l | grep libglib
ii  libglib2.0-0:amd64                                   2.46.2-1ubuntu1                            amd64        GLib library of C routines
ii  libglib2.0-0:i386                                    2.46.2-1ubuntu1                            i386         GLib library of C routines
ii  libglib2.0-bin                                       2.46.2-1ubuntu1                            amd64        Programs for the GLib library
ii  libglib2.0-data                                      2.46.2-1ubuntu1                            all          Common files for GLib library
rc  libglibmm-2.4-1c2a:amd64                             2.42.0-1                                   amd64        C++ wrapper for the GLib toolkit (shared libraries)
ii  libglibmm-2.4-1v5:amd64                              2.45.41.is.2.44.0-0ubuntu2                 amd64        C++ wrapper for the GLib toolkit (shared libraries)
```

**Comment by taviso** [comment]
Thanks for the bug report! I'll try to reproduce, I usually develop on Fedora, so it's possible something is different on Ubuntu.

**Comment by pepa65** [comment]
Not sure if this is any help, but running test/gtk.sh on Ubuntu 16.04 gives:
```
malloc: unknown:0: assertion botched
malloc: block on free list clobbered
Aborting...Aborted (core dumped)
```

**Comment by taviso** [comment]
I don't know why this works perfectly on Fedora and not on Ubuntu, but it's clearly a locking issue. Perhaps bash is using the heap in some way that the slice allocator doesn't like.

It will take some time to debug, but lets just add taskset -p 1 $$ to the gtk.sh example for now, which should at least get it working.
